### ISSUE TITLE
Use different color (variables) for the progress indicator and button hover background

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-skins#3]
I noticed that for both of these two cases, `--highlight-bg-color-hover` is used. But that's a bit problematic because these two cases have different requirements:

- The button hover background must be dark enough to still maintain sufficient contrast to the white foreground icon/text. This is currently not the case with the default color `#3A8BDD`! This results in a contrast of merely 3.54:1, which is not sufficient.
- Contrary, the progress indicator must have a good contrast to the dark background to stand out and be clearly distinguishable. 

So ideally one could use two different colors for both cases, each with slightly different lightness values. In fact, that's what Lisa suggested in her design:

![image](https://github.com/polimediaupv/paella-skins/assets/7419664/839dfa8a-4f10-4c9b-b213-65fe432c3d7c)

(I'm not sure if this is the right repository to open this issue. Maybe this needs to be changed in `paella-core`?)

**Comment by miesgre** [comment]
What other color do you want to use? I will modify the skin with the color you decide.

**Comment by LukasKalbertodt** [comment]
Mhh I would probably just suggest making the button-hover-background a bit darker (e.g. `#2c6fb2`) and the progress indicator a bit brighter (e.g. `#56a0f4`). What do you think about these two colors?

For Tobira, we will adjust the color based on a configured color, so the specific color you chose here is not super important to Tobira.

**Comment by miesgre** [comment]
@LukasKalbertodt I fixed it. Test it at https://polimediaupv.github.io/paella-skins/ and I will publish a new version if its ok.

**Comment by LukasKalbertodt** [comment]
@miesgre Thank you! I tested the current `main` branch and this works for us.
