### ISSUE TITLE
Adapt pre-roll icons to the new design

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-skins#5]
For the newly designed player, I suggest using
https://lucide.dev/icons/play-circle 
instead of
![292250473-9eaf5d46-3eb3-4ce4-aad4-04f8e99a6561](https://github.com/polimediaupv/paella-skins/assets/1752342/31de2131-8c03-4a29-9f44-15abad020198)
and find a new design for the "spinner" 
![296866673-66da904a-9e0b-43af-99f0-27bf97089c8b](https://github.com/polimediaupv/paella-skins/assets/1752342/f26161e8-2614-4a84-a82e-acac30a8f737)
as well.

**Comment by miesgre** [comment]
Currently it is not possible to change those two icons in paella. We have to make changes to paella-core to be able to do it.

Let's see what is the best way to do it. Once the changes are made in paella-core I will update the skin.

https://github.com/polimediaupv/paella-core/issues/358

**Comment by LukasKalbertodt** [comment]
I quickly looked through Lucide icons and I think I'd use [`loader-circle`](https://lucide.dev/icons/loader-circle) for the spinner. Alternatively, there is [`loader`](https://lucide.dev/icons/loader) and [`refresh-cw`](https://lucide.dev/icons/refresh-cw). Something like `loader-circle` is used by OC Studio at least. And I would certainly make it smaller than the current spinner.

**Comment by oas777** [comment]
Thanks, Lukas. I like both loader-circle and loader, but for the sake of consistency with Studio, it's +1 for loader-circle.

**Comment by oas777** [comment]
Miguel, with https://github.com/polimediaupv/paella-core/issues/358 completed, could you add the icons suggested to the skin?

**Comment by miesgre** [comment]
Please check https://polimediaupv.github.io/paella-skins/
If it's ok, I will create a new package for opencast/tobira

**Comment by oas777** [comment]
Thanks, Miguel. Looks good in principle, but could you make both icons the same size and align their position?

**Comment by miesgre** [comment]
> Thanks, Miguel. Looks good in principle, but could you make both icons the same size and align their position?

What do you think now? Make it pixel perfect is complicated as both icons are not positioned in the same way in paella.

**Comment by oas777** [comment]
I think that's good enough, thanks! Do you also have the impression the loading circle is wobbling?

**Comment by miesgre** [comment]
> I think that's good enough, thanks! Do you also have the impression the loading circle is wobbling?

Yes! It's now fixed
